[build]
rustflags = ["-Z", "relro-level=full", "-Z", "macro-backtrace"]
target = "x86_64-unknown-linux-gnu"

[source.crates-io]
replace-with = 'ustc'

[source.ustc]
registry = "git://mirrors.ustc.edu.cn/crates.io-index"
